
version: '3.9'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secretRootPasswd
      - MYSQL_DATABASE=laracamp_db
      - MYSQL_USER=laracamp_user
      - MYSQL_PASSWORD=laracamp_pw
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: