name: Integrate Snyk to Github Action (SCA)

on:
  workflow_call:
    secrets:
      client_id:
        required: true
      api_key:
        required: true
      TELEGRAM_CHAT_ID:
        required: true
      TELEGRAM_TOKEN:
        required: true


jobs:

  soos-sca-analysis:
    name: SOOS SCA Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@v2 # Get Latest Version from https://github.com/marketplace/actions/soos-core-sca
      with:
        project_name: "Laravel Laracamp"
        client_id: ${{ secrets.client_id }}
        api_key: ${{ secrets.api_key }}

    - name: Success Notification
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          🚀 **CI/CD Pipeline Notification** 🚀
          
          **Event**: ${{ github.event_name }}
          **Workflow**: *${{ github.workflow }}*
          **Branch**: *${{ github.ref_name }}*
          **Status**: *Success* ✅

          **More info**: [GitHub Actions Run](${{ github.run_url }})

    - name: Failure Notification
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          🚨 **CI/CD Pipeline Notification** 🚨
            
          **Event**: ${{ github.event_name }}
          **Workflow**: *${{ github.workflow }}*
          **Branch**: *${{ github.ref_name }}*
          **Status**: *Failed* ❌

          **More info**: [GitHub Actions Run](${{ github.run_url }})