name: DAST Scanning Wesbite with Zaproxy

on:
  workflow_call:
    secrets:
      client_id:
        required: true
      api_key:
        required: true

jobs:
  soos_dast_baseline_analysis:
    name: SOOS DAST Baseline Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@v2 # GET Latest Version from https://github.com/marketplace/actions/soos-dast
        with:
          client_id: ${{ secrets.client_id }}
          api_key: ${{ secrets.api_key }}
          project_name: "DAST-Laracamp Website"
          scan_mode: "baseline"
          target_url: "https://www.scorecardresearch.com/"

      - name: Notify Failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚨 **CI/CD Pipeline Notification** 🚨
            
            **Event**: ${{ github.event_name }}
            **Workflow**: *${{ github.workflow }}*
            **Branch**: *${{ github.ref_name }}*
            **Status**: *Failed* ❌

            **More info**: [GitHub Actions Run](${{ github.run_url }})