name: DAST Scanning Wesbite with Zaproxy

on:
  workflow_call:
    inputs:
      website:
        description: 'Website Production'
        required: true
        type: string

    secrets:
      client_id:
        required: true
      api_key:
        required: true

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target:  ${{ inputs.website }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'