name: DAST Scanning Wesbite with Zaproxy

on:
  workflow_call:
    inputs:
      website:
        description: 'Website Production'
        required: true
        type: string

    secrets:
      client_id:
        required: true
      api_key:
        required: true
      GIT_HUB_TOKEN:
        required: true

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GIT_HUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'