name: Update Manifest and Deploy to Staging

on:
  workflow_call:
    secrets:
      GIT_HUB_USERNAME:
        required: true

      GIT_HUB_TOKEN:
        required: true

      ARGOCD_SERVER:
        required: true

      ARGOCD_USER:
        required: true

      ARGOCD_PASS:
        required: true

      TELEGRAM_CHAT_ID:
        required: true
      TELEGRAM_TOKEN:
        required: true

jobs:
  update-manifest:
    name: Update Manifest Kubernetes Laracamp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      # - name: get-images-id
      #   id: image-id
      #   run: |
      #     echo ::set-output name=IMAGE_ID::$(docker images -q nomadd:${{ steps.get-version.outputs.VERSION }}-rc)
          
      - uses: actions/checkout@v3
        name: changing the deployment of git repo
        with:
          repository: 'Gladiator-Squad/Central-Manifest'
          token: ${{ secrets.GIT_HUB_TOKEN }}
          path: central-manifest

      - name: modify the image
        run: |
          cd central-manifest/
          git config user.email eairist@gmail.com
          git config user.name Airist
          sed -i 's|\(image: airist/laracamp:release-\)[^ ]*|\1${{ github.event.release.tag_name }}|' laracamp_deployment/production/laracamp.yaml
          cat laracamp_deployment/production/laracamp.yaml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.event.release.tag_name }}'
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_HUB_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_HUB_TOKEN }}
          RUN_NUMBER: ${{ github.run_number }}          

      - name: Success Notification
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 **CI/CD Pipeline Notification** 🚀
            
            **Event**: ${{ github.event_name }}
            **Workflow**: *${{ github.workflow }}*
            **Branch**: *${{ github.ref_name }}*
            **Status**: *Success* ✅

      - name: Failure Notification
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚨 **CI/CD Pipeline Notification** 🚨
              
            **Event**: ${{ github.event_name }}
            **Workflow**: *${{ github.workflow }}*
            **Branch**: *${{ github.ref_name }}*
            **Status**: *Failed* ❌
            
  # deploy-staging:
  #   name: Deploy Staging Environtment
  #   needs: update-manifest
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: Staging
  #   steps:
  #     - name: ArgoCD Deploy to Staging
  #       run: |
  #         argocd login --insecure  ${{ secrets.ARGOCD_SERVER }} --username  ${{ secrets.ARGOCD_USER }} --password  ${{ secrets.ARGOCD_PASS}}
  #         argocd app create laracamp-stg --project laracamp-stg --repo https://github.com/Gladiator-Squad/Central-Manifest.git --revision staging --path ./laracamp_deployment/staging --dest-namespace laracamp-stg --dest-server https://kubernetes.default.svc --upsert
  #         argocd --grpc-web app sync nomadd-staging --force
  #         argocd --grpc-web app wait nomadd-staging --timeout 600

  #     # - name: Telegram Notification
  #     #   if: ${{ failure() }}
  #     #   uses: xinthink/action-telegram@v1.1
  #     #   with:
  #     #     botToken: ${{ secrets.TELE_BOT_TOKEN }}
  #     #     chatId: ${{ secrets.TELE_CHAT_ID }}
  #     #     jobStatus: ${{ job.status }}
  #     #     skipSuccess: true