name: Update Manifest and Deploy to Staging

on:
  workflow_call:
    secrets:
      GIT_HUB_TOKEN:
        required: true

jobs:
  approval-staging:
    runs-on: ubuntu-latest
    name: Approval Staging
    steps:
      - name: Checkout
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GIT_HUB_TOKEN }}
          approvers: wapol4