name: Docker Compose

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        docker-compose --version
        sudo rm /usr/local/bin/docker-compose
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
  
  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - name: Build Image for Docker compose
      run: |
        docker-compose build app

  deploy:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - name: Build and start Docker Compose
      run: |
        docker-compose up -d

  services:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Check if services are up
      run: |
        docker-compose ps
  
  stop-docker:
    runs-on: ubuntu-latest
    needs: services
    steps:
    - name: Stop Docker Compose
      run: |
        docker-compose down
  
  documentation:
    runs-on: ubuntu-latest
    needs: stop-docker
    steps:
      - name: Checkout code code
        uses: actions/checkout@v2
      - name: Create pages directory
        run: mkdir docs
      - name: Convert markdown to HTML 
        uses: docker://pandoc/core:2.9
        with:
          args: README.md -t html -o docs/index.html
      - name: Deploy Pages site
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs