name: Tag and Push

on:
  workflow_dispatch:
    inputs:
      major:
        description: 'Major version number'
        required: true
      minor:
        description: 'Minor version number'
        required: true
      patch:
        description: 'Patch version number'
        required: true

jobs:
  tag_and_push:
    name: Tag and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Parse version components
        id: parse_version
        run: |
          echo "::set-output name=major::${{ github.event.inputs.major }}"
          echo "::set-output name=minor::${{ github.event.inputs.minor }}"
          echo "::set-output name=patch::${{ github.event.inputs.patch }}"

      - name: Create and push tag
        run: |
          version=v${{ steps.parse_version.outputs.major }}.${{ steps.parse_version.outputs.minor }}.${{ steps.parse_version.outputs.patch }}
          git tag $version
          git push origin $version

      - name: Show tag information
        run: |
          git show ${{ github.sha }}
