name: Push and tag

permissions:
  security-events: write
  pull-requests: read
  contents: write
  id-token: write
  statuses: write
  actions: read
  pages: write

on:
  push:
    branches:
      - test_push-tag
  workflow_dispatch:

jobs:
  tag_and_push:
    name: Tag and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

#       - name: Set up Git
#         run: |
#           git config --local user.email "nasrullah.pandud1@gmail.com"
#           git config --local user.name "Nasrullah Pandu Dewantara"

#       - name: Parse version components
#         id: parse_version
#         run: |
#           echo "::set-output name=major::${{ github.event.inputs.major }}"
#           echo "::set-output name=minor::${{ github.event.inputs.minor }}"
#           echo "::set-output name=patch::${{ github.event.inputs.patch }}"

      # - name: Create and push tag
      #   run: |
      #     version=v${{ steps.parse_version.outputs.major }}.${{ steps.parse_version.outputs.minor }}.${{ steps.parse_version.outputs.patch }}
      #     git tag $version
      #     git push origin $version

      # - name: Show tag information
      #   run: |
      #     git show ${{ github.sha }}
